# Generated by Django 5.1.2 on 2024-10-19 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.location'),
        ),
    ]
