# Generated by Django 5.1.2 on 2024-12-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_location_image_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
